# Generated by Django 6.0.4 on 2026-04-13 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('artist', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='Файл трека')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название плейлиста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(related_name='playlists', to='streaming.track', verbose_name='Треки')),
            ],
        ),
    ]
