# Generated by Django 6.0.4 on 2026-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_playlist_tracks_alter_playlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='Прослушивания'),
        ),
    ]
