# Generated by Django 6.0.5 on 2026-06-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_genre_track_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['artist'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('streaming.track',),
        ),
        migrations.CreateModel(
            name='TrackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='Имя исполнителя')),
                ('track_title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('audio_file', models.FileField(upload_to='submissions/audio/', verbose_name='Аудиофайл')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='submissions/covers/', verbose_name='Обложка')),
                ('comment', models.TextField(blank=True, help_text='Краткое описание трека, ссылки на соцсети и т.д.', verbose_name='Комментарий исполнителя')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт (email / Telegram)')),
                ('status', models.CharField(choices=[('pending', '⏳ На модерации'), ('approved', '✅ Одобрено'), ('rejected', '❌ Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, help_text='Причина отклонения или комментарий — видит только администратор', verbose_name='Заметка администратора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streaming.genre', verbose_name='Жанр')),
                ('published_track', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='streaming.track', verbose_name='Опубликованный трек')),
            ],
            options={
                'verbose_name': 'Заявка на публикацию',
                'verbose_name_plural': 'Заявки на публикацию',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
